### ISSUE TITLE
Rename properties to be more consistent

### ISSUE THREAD

**Issue by MarcGiffing** [MarcGiffing/wicket-spring-boot#25]
see https://github.com/MarcGiffing/wicket-spring-boot/commit/3dfe77835eba3aa8cbf14f3d459b894ac1f26d9d

**Comment by MarcGiffing** [comment]
I've a question regarding the naming of the properties. If we have the take wicket.datastore.cassandra for example. It's located in the wicketstuff project. I don't know if it makes sense to rename it wo wicket.wicketstuff.datastore.cassandra. Is it possible that this functionality is removed to the core? If so we have to rename the property as well, which maybe leads to problems.

Then I've for example wicket.core.csrf. It will be configured with

```
webApplication.getRequestCycleListeners()
```

Should it named to "wicket.core.request-cycle-listener.csrf". Is that intuitionally comprehensible?

I would be very grateful for your opinion @martin-g.

**Comment by martin-g** [comment]
Naming stuff is hard, right? :-)
IMO the important thing is to follow some convention (your own) and keep the properties' names consistent.

For example:
* wicket.core.xyz
* wicket.extensions.xyz
* wicket.stuff.xyz

The deeper the namespace, the better! E.g. `wicket.core.settings.markup.xyz`, `wicket.core.settings.debug.xyz`, `wicket.core.settings.security.xyz`, etc. With YAML this config file will look very natural to read and write.

My 2c.

**Comment by MarcGiffing** [comment]
First idea
```
wicket:
  core:
    settings:
      general: runtime-configuration= development
      requrest-cycle: render-strategy= redirect_to_buffer
      markup: encoding=UTF-8
    requrest-cycle-listener:
      csrf-prevention:
        enabled: true
    storesettings:
      enabled: true
    debugsettings:
      enabled: true
      development-utilities-enabled: true
    serializer:
      deflated:
        enabled: true
    requestmapper:
      cryptmapper:
        enabled: true
  stuff:
    annotationscan:
      enabled: true
    datastore:
      cassandra:
      hazelcast:
      memcached:
      redis:
    htmlcompressor:
    serializer:
      fast2:
      kryo2:
  extension:
    beanvalidation:
      enabled: true
    webjars:
      enabled: true
    development:
      devutils:
        diskstorebrowser:
          enabled: true
        inspector:
          enable-live-sessions-page: true
        statelesschecker:
          enabled: true
      springboot:
        devtools:
          serializer: null
      wicketsource:
        enabled: true
```
